version: '3.9'

services:
  web:
    build: .
    command: |
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=True
      - DATABASE_HOST=db
    volumes:
      - .:/config
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: postgres:16.0
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5


  redis:
    image: redis

  celery:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
      - db
    command: |
       bash -c "celery -A config  worker --loglevel=info  --pool=eventlet"
    volumes:
      - .:/config


  celery_beat:
    build: .
    env_file:
      - .env
    command: |
       bash -c "celery -A config  beat --loglevel=info"
    depends_on:
      - redis
      - db
      - celery
    volumes:
      - .:/config

networks:
  app_neetwork:
    driver: bridge

volumes:
  postgres_data:
  media:
  static_volume: